{{- if .Values.containerSensor.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darktrace-containersensor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containersensor.labels" . | nindent 4 }}
  {{- with .Values.containerSensor.annotations }}
  annotations:
    {{ . | toYaml }}
  {{- end }}
spec:
  replicas: {{ .Values.containerSensor.podReplicas }}
  selector:
    matchLabels:
      app: darktrace-containersensor
      {{- include "containersensor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: darktrace-containersensor
        {{- include "containersensor.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      {{- with .Values.containerSensor.nodeSelector }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.containerSensor.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 6 }}
      {{- end }}
      {{- with .Values.containerSensor.affinity }}
      affinity:
        {{- . | toYaml | nindent 6 }}
      {{- end }}
      serviceAccountName: darktrace-containersensor
      automountServiceAccountToken: true
      volumes:
        - name: subscriber-config
          configMap: 
            name: darktrace-containersensor-config
      containers:
        - name: containersensor
          image: {{ .Values.containerSensor.image.name }}:{{ .Values.containerSensor.image.tag }}
          imagePullPolicy: {{ .Values.containerSensor.image.pullPolicy }}
          {{- if .Values.containerSensor.image.pullSecrets }}
          imagePullSecrets:
            {{- range .Values.containerSensor.image.pullSecrets }}
            - {{.}}
            {{- end }}
          {{- end }}
          resources:
          {{- if .Values.containerSensor.resources }}
            {{ .Values.containerSensor.resources | trim | toYaml | nindent 12 }}
          {{- else }}
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
          {{- end }}
          volumeMounts:
            - name: subscriber-config
              mountPath: /etc/darktrace-metadata-watcher/subscribers.d/kubernetes/default-config.yml
              subPath: default-config.yml
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 998
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: PROVISION_CONFIG
              value: "{{ .Values.containerSensor.config.provisionConfig }}"
            - name: DARKTRACE_URL
              value: {{ .Values.vSensorHostname }}
            - name: DARKTRACE_VERIFY
              value: {{ .Values.vSensorVerifyCertificate | quote }}
            - name: DARKTRACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: darktrace-containersensor-secret
                  key: token
            {{- if .Values.containerSensor.extraEnvs }}
              {{- range $k, $v := .Values.containerSensor.extraEnvs }}
            - name: {{ $k }}
              value: {{ $v }}
              {{- end}}
            {{- end }}
{{- end }}
